include(CMakeFindDependencyMacro)
find_dependency(Boost 1.80 COMPONENTS container json)
find_dependency(mongocxx)
if (BUILD_TESTING)
  find_dependency(hayai)
  find_dependency(zstd)
endif (BUILD_TESTING)
find_dependency(Threads)
find_dependency(ZLIB)
find_dependency(NanoLog)
include(${CMAKE_CURRENT_LIST_DIR}/MongoServiceIlpTargets.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/MongoServiceCommonTargets.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/MongoServiceApiTargets.cmake)
