include(CMakeFindDependencyMacro)
find_dependency(Boost 1.90 COMPONENTS container json)
find_dependency(mongocxx)
find_dependency(Threads)
find_dependency(ZLIB)
find_dependency(NanoLog)
include(${CMAKE_CURRENT_LIST_DIR}/MongoServiceIlpTargets.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/MongoServiceCommonTargets.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/MongoServiceApiTargets.cmake)
