//
// Created by Rakesh on 2020-06-02.
//

#include "db/logger.h"
#include "log/NanoLog.h"
#include "model/configuration.h"
#include "server/service.h"
#include "util/clara.h"

#include <mongocxx/instance.hpp>

#include <iostream>

int main( int argc, char const * const * argv )
{
  using clara::Opt;

  auto& config = spt::model::Configuration::instance();
  bool console = false;
  std::string dir{"logs/"};
  bool help = false;

  auto options = clara::Help(help) |
      Opt(config.port, "port")["-p"]["--port"]("Port on which to listen (default 2000)") |
      Opt(config.threads, "threads")["-n"]["--threads"]("Number of server threads to spawn (default system)") |
      Opt(config.mongoUri, "mongoUri")["-m"]["--mongo-uri"]("MongoDB connection uri.") |
      Opt(config.versionHistoryDatabase, "historyDatabase")["-d"]["--version-history-database"]("MongoDB database to maintain version history in (default versionHistory).") |
      Opt(config.versionHistoryCollection, "historyCollection")["-c"]["--version-history-collection"]("MongoDB collection to store versions of documents (default entities).") |
      Opt(config.metricsDatabase, "metricDatabase")["-s"]["--metric-database"]("MongoDB database to store metrics generated by service (default versionHistory).") |
      Opt(config.metricsCollection, "metricCollection")["-t"]["--metric-collection"]("MongoDB collection to store metrics generated by service (default metrics).") |
      Opt(console, "console")["-e"]["--console"]("Log to console (default false)") |
      Opt(dir, "dir")["-o"]["--dir"]("Log directory (default logs/)");

  auto result = options.parse(clara::Args(argc, argv));
  if (!result)
  {
    std::cerr << "Error in command line: " << result.errorMessage() << std::endl;
    exit(1);
  }

  if ( config.mongoUri.empty() )
  {
    std::cerr << "Mongo URI not configured." << std::endl;
    options.writeToStream( std::cout );
    exit(2);
  }

  if ( help )
  {
    options.writeToStream( std::cout );
    exit(0);
  }

  std::cout << "Starting mongo service with options\n" <<
    "configuration: " << config.str() << '\n' <<
    "console: " << std::boolalpha << console << '\n' <<
    "dir: " << dir << '\n';

  nanolog::initialize( nanolog::GuaranteedLogger(), dir, "mongo-service", console );

  mongocxx::instance instance{ std::make_unique<spt::db::Logger>() };

  return spt::server::run();
}
